"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type LanguageCode = "en" | "hi" | "mr" | "ta";

type TranslationMap = Record<string, string>;

const translations: Record<LanguageCode, TranslationMap> = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.signIn": "Sign In",
    "nav.dashboard": "Dashboard",
    "nav.market": "Market",
    "nav.mandi": "Mandi",
    "nav.climate": "Climate",
    "nav.yield": "Yield",
    "nav.advisor": "Advisor",
    "nav.doctor": "Crop Doctor",
    "nav.subsidies": "Subsidies & Insurance",
    "nav.profile": "Profile",
    "nav.logOut": "Log Out",
    "nav.signOut": "Sign out",
    "nav.signOutConfirm": "Are you sure you want to sign out of AgriSense?",
    "nav.cancel": "Cancel",
    "nav.confirm": "Confirm",
    "nav.language": "Language",

    // Common
    "common.refresh": "Refresh",
    "common.save": "Save changes",
    "common.crop": "Crop",
    "common.state": "State",
    "common.season": "Season",
    "common.acres": "Acres",
    "common.low": "Low Risk",
    "common.moderate": "Moderate Risk",
    "common.high": "High Risk",
    "common.goodMorning": "Good morning",
    "common.yourFarm": "Your farm",
    "common.viewDetails": "View Details",
    "common.loading": "Loading data...",
    "common.search": "Search",
    "common.all": "All",

    // Crops
    "crop.Wheat": "Wheat",
    "crop.Rice": "Rice",
    "crop.Maize": "Maize",
    "crop.Soybean": "Soybean",
    "crop.Cotton": "Cotton",
    "crop.Sugarcane": "Sugarcane",
    "crop.Tomato": "Tomato",
    "crop.Potato": "Potato",
    "crop.Mustard": "Mustard",
    "crop.Chickpea": "Chickpea",
    "crop.Onion": "Onion",

    // Seasons
    "season.Rabi": "Rabi",
    "season.Kharif": "Kharif",
    "season.Zaid": "Zaid",

    // Days of week
    "day.Mon": "Mon",
    "day.Tue": "Tue",
    "day.Wed": "Wed",
    "day.Thu": "Thu",
    "day.Fri": "Fri",
    "day.Sat": "Sat",
    "day.Sun": "Sun",

    // Landing Page
    "landing.heroTitle": "Smarter farming starts with better decisions",
    "landing.heroSubtitle": "Predict demand, prices, and climate risks using AI. AgriSense is your trusted intelligence platform designed specifically for the modern farmer.",
    "landing.getStarted": "Get Started",
    "landing.featureDemandTitle": "Demand Prediction",
    "landing.featureDemandDesc": "Accurately forecast market demand for your crops and plan your selling window.",
    "landing.featurePriceTitle": "Price Forecasting",
    "landing.featurePriceDesc": "Track commodity prices and get notified before significant drops or spikes.",
    "landing.featureClimateTitle": "Climate Risk Alerts",
    "landing.featureClimateDesc": "Anticipate droughts, floods, and frost with localized risk indicators.",
    "landing.howItWorks": "How it works",
    "landing.step1": "Step 1",
    "landing.step1Text": "Input farm data",
    "landing.step2": "Step 2",
    "landing.step2Text": "AI analyzes trends",
    "landing.step3": "Step 3",
    "landing.step3Text": "Get simple insights",
    "landing.footer": "Powered by AgriSense",

    // Auth
    "signin.welcome": "Welcome back",
    "signin.subtitle": "Sign in to access your farm's intelligence.",
    "signin.email": "Email",
    "signin.password": "Password",
    "signin.submit": "Sign In",
    "signin.or": "Or",
    "signin.google": "Continue with Google",
    "signin.tabSignIn": "Sign In",
    "signin.tabSignUp": "Create Account",
    "signin.demo": "Quick Demo Access",
    "signin.noAccount": "New to AgriSense? Create an account",
    "signin.haveAccount": "Already registered? Sign in here",
    "signup.title": "Create your farm account",
    "signup.subtitle": "Start getting AI-driven crop, market, and climate intelligence.",
    "signup.name": "Full Name",
    "signup.location": "State / Location",
    "signup.crop": "Primary Crop",
    "signup.acres": "Farm Size (Acres)",
    "signup.submit": "Create Account & Enter",

    // Dashboard
    "dashboard.yourFarm": "Your farm",
    "dashboard.goodMorning": "Good morning",
    "dashboard.season": "season",
    "dashboard.refresh": "Refresh",
    "dashboard.seasonProgress": "season progress — Week 14 of 26",
    "dashboard.planting": "Planting",
    "dashboard.growing": "Growing",
    "dashboard.harvest": "Harvest",
    "dashboard.pricePerQuintal": "Price (Per Quintal)",
    "dashboard.currentMarketData": "Current Market Data",
    "dashboard.priceChange7d": "7-Day Price Change",
    "dashboard.comparedToLastWeek": "Compared to last week",
    "dashboard.marketVolatility": "Market Volatility",
    "dashboard.basedOnRecentIndex": "Based on recent index",
    "dashboard.climateRiskDetected": "Climate Risk Detected",
    "dashboard.seeFullClimateReport": "See full climate report →",
    "dashboard.marketTellingYou": "What the market is telling you",
    "dashboard.askAdvisorBtn": "Ask the AI Advisor →",
    "dashboard.dataUpdated": "Data updated Just now · Powered by AgriSense ML",

    // Market Page
    "market.title": "Market Intelligence",
    "market.subtitle": "Track 30-day trajectories and 7-day velocity metrics across commodities.",
    "market.selectCrop": "Select Commodity",
    "market.currentPrice": "Current Price",
    "market.change7d": "7-Day Change",
    "market.rolling30d": "30-Day Average",
    "market.volatility": "Price Volatility",
    "market.trend30d": "30-Day Price Trend",
    "market.perQtl": "/ Qtl",
    "market.velocity7d": "7-Day Velocity",
    "market.volatilityScore": "Volatility Score",
    "market.volatilityDesc": "Price fluctuations are within expected seasonal ranges for this period.",

    // Mandi Page
    "mandi.tag": "Mandi comparison",
    "mandi.title": "Best mandi to sell today",
    "mandi.subtitle": "Live modal prices across mandis · Pick the highest-paying market",
    "mandi.filterCommodity": "Filter by Commodity",
    "mandi.all": "All",
    "mandi.bestPriceToday": "Best price today",
    "mandi.perQuintal": "per quintal",
    "mandi.best": "Best",
    "mandi.day7": "7-day",
    "mandi.guideTitle": "How to use mandi comparison to maximise your returns",
    "mandi.guide1": "Modal prices vary across mandis due to local supply-demand dynamics, transport costs, and seasonal buyer activity. Comparing prices before you load your produce can add ₹50–200 per quintal to your net income.",
    "mandi.guide2": "Today, Nashik Mandi is showing the strongest upward momentum for Onion, while Delhi Mandi continues to lead for Tomato. If transport costs to a higher-priced mandi are below the price difference, the move is profitable.",
    "mandi.guide3": "Prices are updated daily from AGMARKNET records. For perishables like Tomato and Onion, check again in the morning before dispatch — intraday swings can be significant.",
    "mandi.footer": "Data sourced from mandi_prices.csv · Updated daily · Powered by AgriSense ML",

    // Climate Page
    "climate.tag": "Climate & weather risk",
    "climate.title": "Weather forecast & field risk",
    "climate.subtitle": "Understand upcoming climate risks",
    "climate.forecast10d": "10-Day Field Forecast",
    "climate.dry": "Dry",
    "climate.lowRain": "Low rain",
    "climate.modRain": "Moderate rain",
    "climate.heavyRain": "Heavy rain",
    "climate.temp": "Temperature",
    "climate.rainRisk": "Precipitation Risk",
    "climate.droughtRisk": "Drought risk",
    "climate.droughtText": "Soil moisture dropping rapidly. High probability of drought stress.",
    "climate.floodRisk": "Flood risk",
    "climate.floodText": "No heavy precipitation expected. Flooding probability negligible.",
    "climate.frostRisk": "Frost risk",
    "climate.frostText": "Temperatures remain safely above 20°C minimum thresholds.",
    "climate.irrigationRec": "Irrigation recommendation",
    "climate.irrigationText": "Based on the dry forecast, irrigate your field on Tuesday and Friday this week. Estimated water needed: 18mm per session.",
    "climate.cropImpactTitle": "How this weather affects your crops",
    "climate.cropImpactText1": "The upcoming heat wave on Wednesday and Thursday (reaching 34°) coincides with the early growing phase of your crop. This heat stress can limit early root development unless soil moisture is actively maintained.",
    "climate.cropImpactText2": "With the moderate rain expected on Friday, we recommend holding off on heavy secondary fertilization until after the showers pass, ensuring nutrients aren't washed away prematurely.",
    "climate.historicalContext": "Rainfall this month is 34% below the 10-year average for your region. Similar patterns in 2019 and 2021 led to 8–12% yield reduction without immediate irrigation.",

    // Yield Page
    "yield.title": "Yield Sandbox Simulator",
    "yield.subtitle": "Adjust environmental metrics to simulate expected output.",
    "yield.configureInputs": "Configure Inputs",
    "yield.crop": "Crop",
    "yield.season": "Season",
    "yield.rainfallVolume": "Rainfall Volume",
    "yield.fertilizerFactor": "Fertilizer Factor",
    "yield.fieldSize": "Field Size",
    "yield.liveEngine": "Live Prediction Engine",
    "yield.totalExpectedAcross": "Total expected output across",
    "yield.confidenceLevel": "Confidence Level",
    "yield.vsHistoricalAvg": "Vs Historical Avg",

    // Advisor Page
    "advisor.title": "Ask the AI Advisor",
    "advisor.subtitle": "Powered by contextual farm insights and real-time market data.",
    "advisor.placeholder": "Ask about market timing, climate risks, or yield confidence...",
    "advisor.send": "Send",
    "advisor.disclaimer": "AgriSense ML responses may produce inaccurate information",
    "advisor.prompt1": "Should I sell my stored wheat this week?",
    "advisor.prompt2": "What crop is best for Rabi season in Punjab?",
    "advisor.prompt3": "How does the current dry spell affect soil moisture?",
    "advisor.initialAssistant": "Hello. I'm your AgriSense AI Advisor. How can I assist you with your farm operations today?",
    "advisor.voiceInput": "Speak question",
    "advisor.listening": "Listening...",
    "advisor.readOut": "Listen",
    "advisor.stopAudio": "Stop audio",

    // Crop Doctor Page
    "doctor.title": "Smart Crop Doctor & Pest Diagnostics",
    "doctor.subtitle": "Diagnose plant diseases, calculate exact chemical dosages for your acres, and prevent crop loss.",
    "doctor.symptomStep": "1. Select Plant Symptoms",
    "doctor.prescriptionStep": "2. Diagnosis & Treatment",
    "doctor.affectedPart": "Affected Plant Part",
    "doctor.leaf": "Leaf",
    "doctor.fruit": "Fruit / Pod",
    "doctor.stem": "Stem",
    "doctor.root": "Root",
    "doctor.selectSymptoms": "Observed Symptoms",
    "doctor.diagnoseBtn": "Diagnose Crop Condition",
    "doctor.diagnosing": "Analyzing Symptoms...",
    "doctor.matchConfidence": "Match Confidence",
    "doctor.cibrcChemical": "CIBRC-Approved Chemical Control",
    "doctor.organicRemedy": "Organic & Biological Remedy",
    "doctor.dosageCalculator": "Acreage Dosage Calculator",
    "doctor.sprayWater": "Total Spray Water Needed",
    "doctor.knapsackTanks": "15-Liter Knapsack Tanks",
    "doctor.batteryTanks": "20-Liter Battery Tanks",
    "doctor.phiDays": "Safe Harvest Interval (PHI)",
    "doctor.listenAudio": "Listen to Spray Instructions",
    "doctor.askAdvisor": "Consult AI Advisor",
    "doctor.sprayAdvisor": "Optimal Spraying Window",
    "doctor.safeToSpray": "Safe to Spray",
    "doctor.doNotSpray": "Hazard: Do Not Spray",

    // Profile Page
    "profile.tag": "Farm profile & Land Geolocation",
    "profile.title": "Your Farm Profile",
    "profile.subtitle": "Keep your farm location, soil profile, and crop parameters up to date for precise AI predictions.",
    "profile.verifiedLand": "Verified Land",
    "profile.farmer": "farmer",
    "profile.formTitle": "Farm & Soil Parameters",
    "profile.syncedMap": "Auto-synced with Land Map",
    "profile.fullName": "Full Name",
    "profile.state": "State / Location",
    "profile.primaryCrop": "Primary Crop",
    "profile.totalArea": "Total Farm Area (Acres)",
    "profile.currentSeason": "Current Season",
    "profile.soilClass": "Soil Classification (From Map)",
    "profile.elevation": "Land Elevation",
    "profile.metersAboveSea": "meters above sea level",
    "profile.summaryTitle": "Active Land & Farm Summary",
    "profile.landArea": "Land Area",
    "profile.soil": "Soil",
    "profile.gpsPin": "GPS Pin",
    "profile.saveBtn": "Save Profile & Land Location",
    "profile.savedNotice": "Profile and Land Data Saved!",

    // Map Component
    "map.title": "Farm Land Geolocation",
    "map.subtitle": "Pinpoint your agricultural land to unlock hyper-local weather & soil analytics.",
    "map.gpsBtn": "Use My GPS Location",
    "map.locating": "Locating Land...",
    "map.searchPlaceholder": "Search district, tehsil or town (e.g. Ludhiana, Nashik, Karnal)...",
    "map.searchBtn": "Search",
    "map.searching": "Searching...",
    "map.dragHint": "Click on map or drag pin to adjust farm coordinates",
    "map.cardElevation": "Coordinates & Elevation",
    "map.altitude": "meters altitude",
    "map.cardSoil": "Soil Classification",
    "map.cardClimate": "Live Land Climate",
    "map.wind": "Wind",
    "map.region": "Region",
    "map.layerSatellite": "Satellite (Esri)",
    "map.layerTerrain": "Terrain (OpenTopo)",
    "map.layerStreets": "Standard Street",
    "map.ndviVigor": "NDVI Vegetative Vigor",
    "map.ndviHealthy": "Healthy Dense Canopy",
    "map.ndviModerate": "Moderate Canopy Density",
    "map.soilHealth": "Soil Moisture & Nitrogen",
    "map.elevationMeters": "m above sea level",
    "map.switchLayer": "Map Layer",

    // Command Center
    "dashboard.commandCenter": "Unified Farm Command Center",
    "dashboard.estimatedRevenue": "Estimated Gross Harvest Revenue",
    "dashboard.expectedOutput": "Expected Output",
    "dashboard.livePrice": "Live Modal Price",
    "dashboard.arbitrageTitle": "Mandi Arbitrage Opportunity",
    "dashboard.highestMarket": "Highest-Paying APMC Mandi",
    "dashboard.netSpread": "Net Spread",
    "dashboard.perQtlMore": "per quintal more",
    "dashboard.sprayWindow": "Agronomic Spray Window",
    "dashboard.spraySafe": "Optimal Spray Window (Safe)",
    "dashboard.sprayHazard": "Weather Hazard (Hold Off Spraying)",
    "dashboard.cropDoctorCard": "Smart Crop Doctor",
    "dashboard.doctorQuickScan": "Diagnose Crop Diseases & Calculate Dosages",
    "dashboard.subsidiesOverview": "Government Subsidies & Benefits",
    "dashboard.unlockedBenefit": "Available Financial Aid",
    "dashboard.satelliteCard": "Satellite Land Intelligence",
    "dashboard.openGisMap": "Open Full GIS Map →",
  },
  hi: {
    // Navigation
    "nav.home": "होम",
    "nav.signIn": "साइन इन",
    "nav.dashboard": "डैशबोर्ड",
    "nav.market": "मार्केट",
    "nav.mandi": "मंडी",
    "nav.climate": "जलवायु",
    "nav.yield": "उपज",
    "nav.advisor": "सलाहकार",
    "nav.doctor": "फसल डॉक्टर",
    "nav.subsidies": "सब्सिडी और बीमा",
    "nav.profile": "प्रोफाइल",
    "nav.logOut": "लॉग आउट",
    "nav.signOut": "साइन आउट",
    "nav.signOutConfirm": "क्या आप वाकई AgriSense से साइन आउट करना चाहते हैं?",
    "nav.cancel": "रद्द करें",
    "nav.confirm": "पुष्टि करें",
    "nav.language": "भाषा",

    // Common
    "common.refresh": "रीफ्रेश",
    "common.save": "सहेजें",
    "common.crop": "फसल",
    "common.state": "राज्य",
    "common.season": "सत्र",
    "common.acres": "एकड़",
    "common.low": "कम जोखिम",
    "common.moderate": "मध्यम जोखिम",
    "common.high": "उच्च जोखिम",
    "common.goodMorning": "शुभ प्रभात",
    "common.yourFarm": "आपका खेत",
    "common.viewDetails": "विवरण देखें",
    "common.loading": "डेटा लोड हो रहा है...",
    "common.search": "खोजें",
    "common.all": "सभी",

    // Crops
    "crop.Wheat": "गेहूं",
    "crop.Rice": "चावल",
    "crop.Maize": "मक्का",
    "crop.Soybean": "सोयाबीन",
    "crop.Cotton": "कपास",
    "crop.Sugarcane": "गन्ना",
    "crop.Tomato": "टमाटर",
    "crop.Potato": "आलू",
    "crop.Mustard": "सरसों",
    "crop.Chickpea": "चना",
    "crop.Onion": "प्याज",

    // Seasons
    "season.Rabi": "रबी",
    "season.Kharif": "खरीफ",
    "season.Zaid": "जायद",

    // Days of week
    "day.Mon": "सोम",
    "day.Tue": "मंगल",
    "day.Wed": "बुध",
    "day.Thu": "गुरु",
    "day.Fri": "शुक्र",
    "day.Sat": "शनि",
    "day.Sun": "रवि",

    // Landing Page
    "landing.heroTitle": "बेहतर फैसलों से शुरू होती है स्मार्ट खेती",
    "landing.heroSubtitle": "AI की मदद से मांग, कीमत और जलवायु जोखिम का अनुमान लगाएं। AgriSense आधुनिक किसान के लिए बनाया गया भरोसेमंद प्लेटफॉर्म है।",
    "landing.getStarted": "शुरू करें",
    "landing.featureDemandTitle": "मांग का अनुमान",
    "landing.featureDemandDesc": "अपनी फसल की बाजार मांग का सही अनुमान लगाएं और सही समय पर बिक्री की योजना बनाएं।",
    "landing.featurePriceTitle": "कीमत पूर्वानुमान",
    "landing.featurePriceDesc": "कमोडिटी कीमतों पर नजर रखें और बड़े उतार-चढ़ाव से पहले अलर्ट पाएं।",
    "landing.featureClimateTitle": "जलवायु जोखिम अलर्ट",
    "landing.featureClimateDesc": "स्थानीय जोखिम संकेतकों के साथ सूखा, बाढ़ और पाला पहले से जानें।",
    "landing.howItWorks": "यह कैसे काम करता है",
    "landing.step1": "चरण 1",
    "landing.step1Text": "खेत का डेटा दर्ज करें",
    "landing.step2": "चरण 2",
    "landing.step2Text": "AI रुझानों का विश्लेषण करता है",
    "landing.step3": "चरण 3",
    "landing.step3Text": "सरल सुझाव प्राप्त करें",
    "landing.footer": "AgriSense द्वारा संचालित",

    // Auth
    "signin.welcome": "वापसी पर स्वागत है",
    "signin.subtitle": "अपने खेत की जानकारी पाने के लिए साइन इन करें।",
    "signin.email": "ईमेल",
    "signin.password": "पासवर्ड",
    "signin.submit": "साइन इन",
    "signin.or": "या",
    "signin.google": "Google से जारी रखें",
    "signin.tabSignIn": "साइन इन",
    "signin.tabSignUp": "खाता बनाएं",
    "signin.demo": "त्वरित डेमो एक्सेस",
    "signin.noAccount": "AgriSense पर नए हैं? नया खाता बनाएं",
    "signin.haveAccount": "पहले से खाता है? यहाँ साइन इन करें",
    "signup.title": "अपना किसान खाता बनाएं",
    "signup.subtitle": "AI-संचालित फसल, बाजार और मौसम की जानकारी पाना शुरू करें।",
    "signup.name": "पूरा नाम",
    "signup.location": "राज्य / स्थान",
    "signup.crop": "मुख्य फसल",
    "signup.acres": "खेत का आकार (एकड़)",
    "signup.submit": "खाता बनाएं और प्रवेश करें",

    // Dashboard
    "dashboard.yourFarm": "आपका खेत",
    "dashboard.goodMorning": "शुभ प्रभात",
    "dashboard.season": "सत्र",
    "dashboard.refresh": "रीफ्रेश करें",
    "dashboard.seasonProgress": "फसल सत्र प्रगति — 26 में से सप्ताह 14",
    "dashboard.planting": "बुवाई",
    "dashboard.growing": "बढ़वार",
    "dashboard.harvest": "कटाई",
    "dashboard.pricePerQuintal": "भाव (प्रति क्विंटल)",
    "dashboard.currentMarketData": "ताजा बाजार डेटा",
    "dashboard.priceChange7d": "7-दिवसीय मूल्य परिवर्तन",
    "dashboard.comparedToLastWeek": "पिछले सप्ताह की तुलना में",
    "dashboard.marketVolatility": "बाजार अस्थिरता",
    "dashboard.basedOnRecentIndex": "हालिया सूचकांक के आधार पर",
    "dashboard.climateRiskDetected": "जलवायु जोखिम का पता चला",
    "dashboard.seeFullClimateReport": "पूरी मौसम रिपोर्ट देखें →",
    "dashboard.marketTellingYou": "बाजार के संकेत और विश्लेषण",
    "dashboard.askAdvisorBtn": "AI सलाहकार से पूछें →",
    "dashboard.dataUpdated": "डेटा अभी अपडेट हुआ · AgriSense ML द्वारा संचालित",

    // Market Page
    "market.title": "बाजार आसूचना व विश्लेषण",
    "market.subtitle": "विभिन्न फसलों के 30-दिवसीय रुझान और 7-दिवसीय गतिशीलता देखें।",
    "market.selectCrop": "फसल चुनें",
    "market.currentPrice": "वर्तमान भाव",
    "market.change7d": "7 दिनों का बदलाव",
    "market.rolling30d": "30 दिनों का औसत",
    "market.volatility": "मूल्य अस्थिरता",
    "market.trend30d": "30-दिवसीय मूल्य रुझान",
    "market.perQtl": "/ क्विंटल",
    "market.velocity7d": "7-दिवसीय गति",
    "market.volatilityScore": "अस्थिरता स्कोर",
    "market.volatilityDesc": "मूल्य उतार-चढ़ाव इस अवधि के लिए अपेक्षित मौसमी सीमाओं के भीतर हैं।",

    // Mandi Page
    "mandi.tag": "मंडी तुलना",
    "mandi.title": "आज बेचने के लिए सबसे अच्छी मंडी",
    "mandi.subtitle": "सभी मंडियों में लाइव थोक भाव · सर्वाधिक लाभ देने वाली मंडी चुनें",
    "mandi.filterCommodity": "फसल के अनुसार फ़िल्टर करें",
    "mandi.all": "सभी फसलें",
    "mandi.bestPriceToday": "आज का सर्वोत्तम भाव",
    "mandi.perQuintal": "प्रति क्विंटल",
    "mandi.best": "सर्वश्रेष्ठ",
    "mandi.day7": "7-दिन",
    "mandi.guideTitle": "मुनाफा बढ़ाने के लिए मंडी तुलना का उपयोग कैसे करें",
    "mandi.guide1": "स्थानीय मांग, आपूर्ति और परिवहन लागत के कारण मंडियों के भावों में अंतर होता है। उपज भेजने से पहले भाव जांचने से आपको प्रति क्विंटल ₹50–200 अतिरिक्त आय मिल सकती है।",
    "mandi.guide2": "आज प्याज के लिए नासिक मंडी में तेजी का रुख है, जबकि टमाटर के लिए दिल्ली मंडी आगे है। यदि परिवहन लागत मूल्य अंतर से कम है तो वहां बेचना लाभदायक है।",
    "mandi.guide3": "भाव प्रतिदिन AGMARKNET से अपडेट किए जाते हैं। टमाटर और प्याज जैसी खराब होने वाली फसलों के लिए सुबह भेजने से पहले पुनः जांच करें।",
    "mandi.footer": "डेटा स्रोत mandi_prices.csv · प्रतिदिन अपडेट · AgriSense ML द्वारा संचालित",

    // Climate Page
    "climate.tag": "जलवायु एवं मौसम जोखिम",
    "climate.title": "मौसम पूर्वानुमान एवं खेत जोखिम",
    "climate.subtitle": "आने वाले मौसम की परिस्थितियों और खेत के जोखिमों को समझें",
    "climate.forecast10d": "10-दिवसीय खेत मौसम पूर्वानुमान",
    "climate.dry": "शुष्क / सूखा",
    "climate.lowRain": "हल्की वर्षा",
    "climate.modRain": "मध्यम वर्षा",
    "climate.heavyRain": "भारी वर्षा",
    "climate.temp": "तापमान",
    "climate.rainRisk": "वर्षा जोखिम",
    "climate.droughtRisk": "सूखे का जोखिम",
    "climate.droughtText": "मिट्टी की नमी तेजी से घट रही है। फसल पर सूखे का प्रभाव पड़ने की आशंका है।",
    "climate.floodRisk": "बाढ़ का जोखिम",
    "climate.floodText": "भारी वर्षा का अनुमान नहीं है। जलभराव या बाढ़ की संभावना नगण्य है।",
    "climate.frostRisk": "पाले का जोखिम",
    "climate.frostText": "तापमान 20°C से ऊपर सुरक्षित स्तर पर बना रहेगा।",
    "climate.irrigationRec": "सिंचाई संबंधी सिफारिश",
    "climate.irrigationText": "शुष्क मौसम को देखते हुए, इस सप्ताह मंगलवार और शुक्रवार को खेत की सिंचाई करें। प्रति सत्र अनुशंसित जल: 18 मिमी।",
    "climate.cropImpactTitle": "यह मौसम आपकी फसल को कैसे प्रभावित करता है",
    "climate.cropImpactText1": "बुधवार और गुरुवार को पड़ने वाली गर्मी (34°C तक) फसल की प्रारंभिक वृद्धि अवस्था से मेल खाती है। पर्याप्त नमी बनाए रखना आवश्यक है।",
    "climate.cropImpactText2": "शुक्रवार को होने वाली बारिश को देखते हुए, बारिश से पहले भारी खाद डालने से बचें ताकि पोषक तत्व बह न जाएं।",
    "climate.historicalContext": "इस महीने की वर्षा आपके क्षेत्र के 10 वर्षों के औसत से 34% कम है। तत्काल सिंचाई सुनिश्चित करें।",

    // Yield Page
    "yield.title": "फसल उपज सिम्युलेटर",
    "yield.subtitle": "अपेक्षित उत्पादन का सटीक अनुमान लगाने के लिए कारक समायोजित करें।",
    "yield.configureInputs": "इनपुट कॉन्फ़िगर करें",
    "yield.crop": "फसल",
    "yield.season": "सत्र / मौसम",
    "yield.rainfallVolume": "वर्षा की मात्रा",
    "yield.fertilizerFactor": "उर्वरक कारक",
    "yield.fieldSize": "खेत का आकार",
    "yield.liveEngine": "लाइव प्रेडिक्शन इंजन",
    "yield.totalExpectedAcross": "कुल अनुमानित उत्पादन",
    "yield.confidenceLevel": "विश्वसनीयता स्तर",
    "yield.vsHistoricalAvg": "ऐतिहासिक औसत की तुलना में",

    // Advisor Page
    "advisor.title": "AI कृषि सलाहकार से पूछें",
    "advisor.subtitle": "आपके खेत की स्थिति और वास्तविक बाजार डेटा पर आधारित सलाह।",
    "advisor.placeholder": "बाजार समय, मौसम जोखिम, या फसल उपज के बारे में पूछें...",
    "advisor.send": "भेजें",
    "advisor.disclaimer": "AgriSense ML द्वारा तैयार उत्तर सूचनात्मक उद्देश्यों के लिए हैं",
    "advisor.prompt1": "क्या मुझे इस सप्ताह संग्रहीत गेहूं बेचना चाहिए?",
    "advisor.prompt2": "पंजाब में रबी सत्र के लिए कौन सी फसल सबसे अच्छी है?",
    "advisor.prompt3": "वर्तमान शुष्क मौसम मिट्टी की नमी को कैसे प्रभावित करता है?",
    "advisor.initialAssistant": "नमस्ते। मैं आपका AgriSense AI कृषि सलाहकार हूँ। आज मैं आपकी खेती में कैसे सहायता कर सकता हूँ?",
    "advisor.voiceInput": "बोलकर पूछें",
    "advisor.listening": "सुन रहा है...",
    "advisor.readOut": "सुनें",
    "advisor.stopAudio": "आवाज रोकें",

    // Crop Doctor Page
    "doctor.title": "स्मार्ट फसल डॉक्टर एवं कीट निदान",
    "doctor.subtitle": "पौधों के रोगों की पहचान करें, अपने खेत के एकड़ अनुसार सटीक दवा की मात्रा जानें और फसल बचाएं।",
    "doctor.symptomStep": "1. पौधे के लक्षण चुनें",
    "doctor.prescriptionStep": "2. रोग निदान एवं उपचार",
    "doctor.affectedPart": "प्रभावित भाग",
    "doctor.leaf": "पत्ती",
    "doctor.fruit": "फल / फली",
    "doctor.stem": "तना",
    "doctor.root": "जड़",
    "doctor.selectSymptoms": "दिखाई देने वाले लक्षण",
    "doctor.diagnoseBtn": "रोग की जांच करें",
    "doctor.diagnosing": "लक्षणों का विश्लेषण हो रहा है...",
    "doctor.matchConfidence": "सटीकता प्रतिशत",
    "doctor.cibrcChemical": "केंद्रीय कीटनाशक बोर्ड द्वारा प्रमाणित दवा",
    "doctor.organicRemedy": "जैविक एवं प्राकृतिक उपचार",
    "doctor.dosageCalculator": "खेत के अनुसार दवा कैलकुलेटर",
    "doctor.sprayWater": "छिड़काव हेतु कुल पानी",
    "doctor.knapsackTanks": "15-लीटर वाले स्प्रे पंप",
    "doctor.batteryTanks": "20-लीटर वाले बैटरी पंप",
    "doctor.phiDays": "कटाई से पहले सुरक्षित अंतराल (PHI)",
    "doctor.listenAudio": "छिड़काव निर्देश सुनें",
    "doctor.askAdvisor": "AI सलाहकार से पूछें",
    "doctor.sprayAdvisor": "छिड़काव के लिए सही समय",
    "doctor.safeToSpray": "छिड़काव के लिए अनुकूल",
    "doctor.doNotSpray": "सावधान: छिड़काव न करें",

    // Profile Page
    "profile.tag": "किसान प्रोफाइल एवं भूमि भूस्थान",
    "profile.title": "आपकी किसान प्रोफाइल",
    "profile.subtitle": "सटीक AI भविष्यवाणियों के लिए अपने खेत का स्थान, मिट्टी और फसल डेटा अपडेट रखें।",
    "profile.verifiedLand": "सत्यापित भूमि",
    "profile.farmer": "किसान",
    "profile.formTitle": "खेत एवं मिट्टी के पैरामीटर",
    "profile.syncedMap": "नक्शे के साथ स्वतः समन्वयित",
    "profile.fullName": "पूरा नाम",
    "profile.state": "राज्य / स्थान",
    "profile.primaryCrop": "मुख्य फसल",
    "profile.totalArea": "खेत का कुल क्षेत्रफल (एकड़)",
    "profile.currentSeason": "वर्तमान सत्र",
    "profile.soilClass": "मिट्टी वर्गीकरण (नक्शे से)",
    "profile.elevation": "भूमि की ऊंचाई",
    "profile.metersAboveSea": "मीटर समुद्र तल से ऊपर",
    "profile.summaryTitle": "सक्रिय भूमि एवं खेत सारांश",
    "profile.landArea": "जमीन का क्षेत्रफल",
    "profile.soil": "मिट्टी",
    "profile.gpsPin": "GPS पिन",
    "profile.saveBtn": "प्रोफाइल और भूमि स्थान सहेजें",
    "profile.savedNotice": "प्रोफाइल और भूमि डेटा सफलतापूर्वक सहेजा गया!",

    // Map Component
    "map.title": "खेत का भौगोलिक स्थान",
    "map.subtitle": "स्थानीय मौसम और मिट्टी विश्लेषण के लिए अपने खेत को मैप पर चिन्हित करें।",
    "map.gpsBtn": "मेरा GPS स्थान उपयोग करें",
    "map.locating": "स्थान खोजा जा रहा है...",
    "map.searchPlaceholder": "जिला, तहसील या शहर खोजें (उदा. लुधियाना, नासिक, करनाल)...",
    "map.searchBtn": "खोजें",
    "map.searching": "खोज रहे हैं...",
    "map.dragHint": "खेत के निर्देशांक बदलने के लिए मैप पर क्लिक करें या पिन खींचें",
    "map.cardElevation": "निर्देशांक एवं ऊंचाई",
    "map.altitude": "मीटर ऊंचाई",
    "map.cardSoil": "मिट्टी का प्रकार",
    "map.cardClimate": "खेत का वास्तविक मौसम",
    "map.wind": "हवा",
    "map.region": "क्षेत्र",
    "map.layerSatellite": "उपग्रह दृश्य (Esri)",
    "map.layerTerrain": "भू-भाग (OpenTopo)",
    "map.layerStreets": "मानक सड़क",
    "map.ndviVigor": "NDVI वनस्पति शक्ति",
    "map.ndviHealthy": "स्वस्थ सघन फसल",
    "map.ndviModerate": "मध्यम फसल सघनता",
    "map.soilHealth": "मिट्टी नमी एवं नाइट्रोजन",
    "map.elevationMeters": "मीटर समुद्र तल से ऊपर",
    "map.switchLayer": "मैप लेयर",

    // Command Center
    "dashboard.commandCenter": "एकीकृत कृषि कमांड सेंटर",
    "dashboard.estimatedRevenue": "अनुमानित कुल फसल राजस्व",
    "dashboard.expectedOutput": "अनुमानित उत्पादन",
    "dashboard.livePrice": "ताज़ा APMC मॉडल भाव",
    "dashboard.arbitrageTitle": "मंडी आर्बिट्राज अवसर",
    "dashboard.highestMarket": "सर्वोत्तम भाव वाली APMC मंडी",
    "dashboard.netSpread": "अतिरिक्त मुनाफा",
    "dashboard.perQtlMore": "प्रति क्विंटल अधिक",
    "dashboard.sprayWindow": "कीटनाशक छिड़काव खिड़की",
    "dashboard.spraySafe": "छिड़काव हेतु उत्तम समय (सुरक्षित)",
    "dashboard.sprayHazard": "मौसम खतरा (छिड़काव स्थगित रखें)",
    "dashboard.cropDoctorCard": "स्मार्ट फसल डॉक्टर",
    "dashboard.doctorQuickScan": "फसल रोगों की पहचान और सही खुराक जानें",
    "dashboard.subsidiesOverview": "सरकारी योजनाएं व सब्सिडी लाभ",
    "dashboard.unlockedBenefit": "उपलब्ध वित्तीय सहायता",
    "dashboard.satelliteCard": "उपग्रह भूमि विश्लेषण",
    "dashboard.openGisMap": "विस्तृत GIS मैप खोलें →",
  },
  mr: {
    // Navigation
    "nav.home": "मुख्यपृष्ठ",
    "nav.signIn": "साइन इन",
    "nav.dashboard": "डॅशबोर्ड",
    "nav.market": "बाजार",
    "nav.mandi": "मंडी",
    "nav.climate": "हवामान",
    "nav.yield": "उत्पन्न",
    "nav.advisor": "सल्लागार",
    "nav.subsidies": "अनुदान आणि विमा",
    "nav.profile": "प्रोफाइल",
    "nav.logOut": "लॉग आउट",
    "nav.signOut": "साइन आउट",
    "nav.signOutConfirm": "तुम्हाला AgriSense मधून साइन आउट करायचे आहे का?",
    "nav.cancel": "रद्द करा",
    "nav.confirm": "पुष्टी करा",
    "nav.language": "भाषा",

    // Common
    "common.refresh": "रिफ्रेश",
    "common.save": "बदल सेव्ह करा",
    "common.crop": "पीक",
    "common.state": "राज्य",
    "common.season": "हंगाम",
    "common.acres": "एकर",
    "common.low": "कमी जोखीम",
    "common.moderate": "मध्यम जोखीम",
    "common.high": "जास्त जोखीम",
    "common.goodMorning": "शुभ सकाळ",
    "common.yourFarm": "तुमचे शेत",
    "common.viewDetails": "तपशील पहा",
    "common.loading": "माहिती लोड होत आहे...",
    "common.search": "शोधा",
    "common.all": "सर्व",

    // Crops
    "crop.Wheat": "गहू",
    "crop.Rice": "तांदूळ",
    "crop.Maize": "मका",
    "crop.Soybean": "सोयाबीन",
    "crop.Cotton": "कापूस",
    "crop.Sugarcane": "ऊस",
    "crop.Tomato": "टोमॅटो",
    "crop.Potato": "बटाटा",
    "crop.Mustard": "मोहरी",
    "crop.Chickpea": "हरभरा",
    "crop.Onion": "कांदा",

    // Seasons
    "season.Rabi": "रब्बी",
    "season.Kharif": "खरीप",
    "season.Zaid": "उन्हाळी (झैद)",

    // Days of week
    "day.Mon": "सोम",
    "day.Tue": "मंगळ",
    "day.Wed": "बुध",
    "day.Thu": "गुरु",
    "day.Fri": "शुक्र",
    "day.Sat": "शनि",
    "day.Sun": "रवि",

    // Landing Page
    "landing.heroTitle": "चांगले निर्णय म्हणजे स्मार्ट शेतीची सुरुवात",
    "landing.heroSubtitle": "AI वापरून मागणी, किंमत आणि हवामान जोखीम यांचे भाकीत करा. AgriSense हा आधुनिक शेतकऱ्यासाठी तयार केलेला विश्वासार्ह प्लॅटफॉर्म आहे.",
    "landing.getStarted": "सुरुवात करा",
    "landing.featureDemandTitle": "मागणीचा अंदाज",
    "landing.featureDemandDesc": "तुमच्या पिकांची बाजारातील मागणी अचूक ओळखा आणि विक्रीची योग्य वेळ ठरवा.",
    "landing.featurePriceTitle": "किंमत अंदाज",
    "landing.featurePriceDesc": "बाजारभावावर लक्ष ठेवा आणि मोठ्या चढउतारांपूर्वी सूचना मिळवा.",
    "landing.featureClimateTitle": "हवामान जोखीम सूचना",
    "landing.featureClimateDesc": "स्थानिक निर्देशकांद्वारे दुष्काळ, पूर आणि थंडीचा अंदाज आधी घ्या.",
    "landing.howItWorks": "हे कसे काम करते",
    "landing.step1": "टप्पा 1",
    "landing.step1Text": "शेताची माहिती भरा",
    "landing.step2": "टप्पा 2",
    "landing.step2Text": "AI ट्रेंडचे विश्लेषण करते",
    "landing.step3": "टप्पा 3",
    "landing.step3Text": "सोपे सल्ले मिळवा",
    "landing.footer": "AgriSense द्वारे समर्थित",

    // Auth
    "signin.welcome": "पुन्हा स्वागत आहे",
    "signin.subtitle": "तुमच्या शेताची माहिती पाहण्यासाठी साइन इन करा.",
    "signin.email": "ईमेल",
    "signin.password": "पासवर्ड",
    "signin.submit": "साइन इन",
    "signin.or": "किंवा",
    "signin.google": "Google सह सुरू ठेवा",
    "signin.tabSignIn": "साइन इन",
    "signin.tabSignUp": "खाते तयार करा",
    "signin.demo": "डेमो प्रवेश",
    "signin.noAccount": "AgriSense वर नवीन आहात? नवीन खाते तयार करा",
    "signin.haveAccount": "आधीच खाते आहे का? येथे साइन इन करा",
    "signup.title": "आपले शेतकरी खाते तयार करा",
    "signup.subtitle": "AI-आधारित पीक, बाजार आणि हवामान माहिती मिळवण्यास सुरुवात करा.",
    "signup.name": "पूर्ण नाव",
    "signup.location": "राज्य / स्थान",
    "signup.crop": "मुख्य पीक",
    "signup.acres": "शेतीचा आकार (एकर)",
    "signup.submit": "खाते तयार करा आणि सुरू करा",

    // Dashboard
    "dashboard.yourFarm": "तुमचे शेत",
    "dashboard.goodMorning": "शुभ सकाळ",
    "dashboard.season": "हंगाम",
    "dashboard.refresh": "रिफ्रेश",
    "dashboard.seasonProgress": "हंगाम प्रगती — २६ पैकी आठवडा १४",
    "dashboard.planting": "पेरणी",
    "dashboard.growing": "वाढ",
    "dashboard.harvest": "कापणी",
    "dashboard.pricePerQuintal": "भाव (प्रति क्विंटल)",
    "dashboard.currentMarketData": "सध्याचा बाजार डेटा",
    "dashboard.priceChange7d": "७ दिवसांतील भाव बदल",
    "dashboard.comparedToLastWeek": "मागील आठवड्याच्या तुलनेत",
    "dashboard.marketVolatility": "बाजार अस्थिरता",
    "dashboard.basedOnRecentIndex": "नजीकच्या निर्देशांकावर आधारित",
    "dashboard.climateRiskDetected": "हवामान जोखीम आढळली",
    "dashboard.seeFullClimateReport": "संपूर्ण हवामान अहवाल पहा →",
    "dashboard.marketTellingYou": "बाजार परिस्थिती आणि संकेत",
    "dashboard.askAdvisorBtn": "AI सल्लागारास विचारा →",
    "dashboard.dataUpdated": "डेटा आत्ताच अद्ययावत केला · AgriSense ML द्वारे समर्थित",

    // Market Page
    "market.title": "बाजार माहिती व विश्लेषण",
    "market.subtitle": "विविध पिकांच्या ३० दिवसांचा भाव कल आणि ७ दिवसांची गती तपासा.",
    "market.selectCrop": "पीक निवडा",
    "market.currentPrice": "सध्याचा भाव",
    "market.change7d": "७ दिवसांतील बदल",
    "market.rolling30d": "३० दिवसांची सरासरी",
    "market.volatility": "किंमत अस्थिरता",
    "market.trend30d": "३० दिवसांचा भाव कल",
    "market.perQtl": "/ क्विंटल",
    "market.velocity7d": "७ दिवसांची गती",
    "market.volatilityScore": "अस्थिरता स्कोअर",
    "market.volatilityDesc": "किमतीतील चढउतार या कालावधीसाठी अपेक्षित मर्यादेत आहेत.",

    // Mandi Page
    "mandi.tag": "बाजार समिती तुलना",
    "mandi.title": "आज शेतमाल विकण्यासाठी सर्वोत्तम बाजार समिती",
    "mandi.subtitle": "थेट बाजार भाव तपासा · सर्वाधिक दर देणारी बाजार समिती निवडा",
    "mandi.filterCommodity": "पिकानुसार निवडा",
    "mandi.all": "सर्व पिके",
    "mandi.bestPriceToday": "आजचा सर्वोत्तम भाव",
    "mandi.perQuintal": "प्रति क्विंटल",
    "mandi.best": "सर्वोत्तम",
    "mandi.day7": "७-दिवस",
    "mandi.guideTitle": "नफा वाढवण्यासाठी बाजार समिती भाव तुलनेचा वापर कसा करावा",
    "mandi.guide1": "स्थानिक मागणी, आवक आणि वाहतूक खर्चामुळे विविध बाजार समित्यांमध्ये दरात फरक असतो. माल पाठवण्यापूर्वी भाव तपासल्यास प्रति क्विंटल ₹५०–२०० जास्तीचा नफा मिळू शकतो.",
    "mandi.guide2": "आज कांद्यासाठी नाशिक बाजार समितीत तेजी दिसून येत आहे, तर टोमॅटोसाठी दिल्ली आघाडीवर आहे. वाहतूक खर्चापेक्षा दरातील फरक जास्त असल्यास तिथे विक्री फायदेशीर ठरते.",
    "mandi.guide3": "दर दररोज AGMARKNET वरून अद्ययावत केले जातात. कांदा आणि टोमॅटोसारख्या नाशवंत मालासाठी सकाळी पाठवण्यापूर्वी पुन्हा दर तपासावेत.",
    "mandi.footer": "माहिती स्रोत mandi_prices.csv · दररोज अद्ययावत · AgriSense ML द्वारे",

    // Climate Page
    "climate.tag": "हवामान आणि जोखीम अंदाज",
    "climate.title": "हवामान अंदाज व शेती जोखीम",
    "climate.subtitle": "शेतावरील संभाव्य हवामान बदल आणि जोखीम आधीच ओळखा",
    "climate.forecast10d": "१० दिवसांचा शेती हवामान अंदाज",
    "climate.dry": "कोरडे / ऊन",
    "climate.lowRain": "हलका पाऊस",
    "climate.modRain": "मध्यम पाऊस",
    "climate.heavyRain": "मुसळधार पाऊस",
    "climate.temp": "तापमान",
    "climate.rainRisk": "पावसाची जोखीम",
    "climate.droughtRisk": "दुष्काळ जोखीम",
    "climate.droughtText": "मातीतील ओलावा वेगाने कमी होत आहे. पिकावर पाण्याचा ताण येण्याची शक्यता आहे.",
    "climate.floodRisk": "पूर जोखीम",
    "climate.floodText": "अतिवृष्टीचा अंदाज नाही. पाणी साचण्याची शक्यता अत्यल्प आहे.",
    "climate.frostRisk": "थंडी / धुक्याची जोखीम",
    "climate.frostText": "तापमान २० अंश सेल्सिअसच्या सुरक्षित पातळीवर राहील.",
    "climate.irrigationRec": "पाणी व्यवस्थापन सल्ला",
    "climate.irrigationText": "कोरड्या हवामानाचा अंदाज असल्याने या आठवड्यात मंगळवार आणि शुक्रवारी शेताला पाणी द्यावे. प्रति सत्र पाणी: १८ मिमी.",
    "climate.cropImpactTitle": "या हवामानाचा पिकावर होणारा परिणाम",
    "climate.cropImpactText1": "बुधवार आणि गुरुवारी येणारी उष्णतेची लाट (३४ अंशांपर्यंत) पिकाच्या सुरुवातीच्या वाढीवर परिणाम करू शकते. मातीतील ओलावा टिकवून ठेवणे आवश्यक आहे.",
    "climate.cropImpactText2": "शुक्रवारी मध्यम पाऊस अपेक्षित असल्याने, खते वाहून जाऊ नयेत म्हणून पावसापूर्वी खत देणे टाळावे.",
    "climate.historicalContext": "या महिन्यात आपल्या भागातील पाऊस १० वर्षांच्या सरासरीपेक्षा ३४% कमी आहे. योग्य वेळी पाणी देणे गरजेचे आहे.",

    // Yield Page
    "yield.title": "पीक उत्पादन सिम्युलेटर",
    "yield.subtitle": "अपेक्षित उत्पादनाचा अचूक अंदाज घेण्यासाठी विविध घटक तपासा.",
    "yield.configureInputs": "घटक निवडा",
    "yield.crop": "पीक",
    "yield.season": "हंगाम",
    "yield.rainfallVolume": "पावसाचे प्रमाण",
    "yield.fertilizerFactor": "खताचे प्रमाण",
    "yield.fieldSize": "शेतीचा आकार",
    "yield.liveEngine": "थेट अंदाज प्रणाली",
    "yield.totalExpectedAcross": "एकूण अंदाजित उत्पादन",
    "yield.confidenceLevel": "अचूकता पातळी",
    "yield.vsHistoricalAvg": "ऐतिहासिक सरासरीच्या तुलनेत",

    // Advisor Page
    "advisor.title": "AI कृषी सल्लागारास विचारा",
    "advisor.subtitle": "आपल्या शेताची स्थिती आणि थेट बाजार माहितीवर आधारित तज्ञ सल्ला.",
    "advisor.placeholder": "बाजार भाव, हवामान जोखीम किंवा पीक उत्पादनाबाबत विचारा...",
    "advisor.send": "पाठवा",
    "advisor.disclaimer": "AgriSense ML द्वारे दिलेली उत्तरे मार्गदर्शनासाठी आहेत",
    "advisor.prompt1": "मी या आठवड्यात साठवलेला गहू विकावा का?",
    "advisor.prompt2": "महाराष्ट्रात रब्बी हंगामासाठी कोणते पीक उत्तम आहे?",
    "advisor.prompt3": "सध्याच्या कोरड्या हवामानाचा जमिनीच्या ओलाव्यावर काय परिणाम होईल?",
    "advisor.initialAssistant": "नमस्कार. मी तुमचा AgriSense AI शेती सल्लागार आहे. आज मी तुम्हाला कशी मदत करू शकतो?",
    "advisor.voiceInput": "बोलून विचारा",
    "advisor.listening": "ऐकत आहे...",
    "advisor.readOut": "ऐका",
    "advisor.stopAudio": "आवाज थांबवा",

    // Profile Page
    "profile.tag": "शेतकरी प्रोफाइल व शेतजमीन स्थान",
    "profile.title": "आपली शेतकरी प्रोफाइल",
    "profile.subtitle": "अचूक AI अंदाजांसाठी आपल्या शेताची जागा, माती आणि पिकांची माहिती अद्ययावत ठेवा.",
    "profile.verifiedLand": "सत्यापित शेतजमीन",
    "profile.farmer": "शेतकरी",
    "profile.formTitle": "शेत आणि मातीचे घटक",
    "profile.syncedMap": "नकाशाशी आपोआप जोडलेले",
    "profile.fullName": "पूर्ण नाव",
    "profile.state": "राज्य / स्थान",
    "profile.primaryCrop": "मुख्य पीक",
    "profile.totalArea": "एकूण शेती क्षेत्र (एकर)",
    "profile.currentSeason": "चालू हंगाम",
    "profile.soilClass": "मातीचा प्रकार (नकाशावरून)",
    "profile.elevation": "जमिनीची उंची",
    "profile.metersAboveSea": "मीटर समुद्रसपाटीपासून",
    "profile.summaryTitle": "सक्रिय शेतजमीन व शेत सारांश",
    "profile.landArea": "शेतजमीन क्षेत्र",
    "profile.soil": "माती",
    "profile.gpsPin": "GPS पिन",
    "profile.saveBtn": "प्रोफाइल आणि शेताचे स्थान सेव्ह करा",
    "profile.savedNotice": "प्रोफाइल आणि जमिनीची माहिती यशस्वीरीत्या सेव्ह झाली!",

    // Map Component
    "map.title": "शेताचे भौगोलिक स्थान",
    "map.subtitle": "स्थानिक हवामान आणि माती विश्लेषणासाठी आपले शेत नकाशावर निश्चित करा.",
    "map.gpsBtn": "माझे GPS स्थान वापरा",
    "map.locating": "स्थान शोधत आहे...",
    "map.searchPlaceholder": "जिल्हा, तालुका किंवा गाव शोधा (उदा. नाशिक, पुणे, सातारा)...",
    "map.searchBtn": "शोधा",
    "map.searching": "शोधत आहे...",
    "map.dragHint": "शेताचे गुणक बदलण्यासाठी नकाशावर क्लिक करा किंवा पिन हलवा",
    "map.cardElevation": "स्थान व जमिनीची उंची",
    "map.altitude": "मीटर उंची",
    "map.cardSoil": "मातीचा प्रकार",
    "map.cardClimate": "शेताचे थेट हवामान",
    "map.wind": "वारा",
    "map.region": "विभाग",
    "map.layerSatellite": "उपग्रह दृश्य (Esri)",
    "map.layerTerrain": "भूरूप (OpenTopo)",
    "map.layerStreets": "रस्ता नकाशा",
    "map.ndviVigor": "NDVI वनस्पती आरोग्य",
    "map.ndviHealthy": "निरोगी दाट पीक",
    "map.ndviModerate": "मध्यम पीक घनता",
    "map.soilHealth": "मातीतील ओलावा व नायट्रोजन",
    "map.elevationMeters": "मीटर समुद्रसपाटीपासून",
    "map.switchLayer": "नकाशा लेयर",

    // Command Center
    "dashboard.commandCenter": "एकात्मिक शेत कमांड सेंटर",
    "dashboard.estimatedRevenue": "अंदाजे एकूण पीक महसूल",
    "dashboard.expectedOutput": "अपेक्षित उत्पादन",
    "dashboard.livePrice": "थेट APMC बाजार भाव",
    "dashboard.arbitrageTitle": "मंडी नफा संधी",
    "dashboard.highestMarket": "सर्वाधिक भाव देणारी APMC बाजार समिती",
    "dashboard.netSpread": "अतिरिक्त नफा",
    "dashboard.perQtlMore": "प्रति क्विंटल जास्त",
    "dashboard.sprayWindow": "औषध फवारणी वेळ",
    "dashboard.spraySafe": "फवारणीसाठी उत्तम वेळ (सुरक्षित)",
    "dashboard.sprayHazard": "हवामान धोका (फवारणी थांबवा)",
    "dashboard.cropDoctorCard": "स्मार्ट पीक डॉक्टर",
    "dashboard.doctorQuickScan": "पीक रोगांचे निदान व अचूक औषध मात्रा",
    "dashboard.subsidiesOverview": "शासकीय योजना व अनुदान लाभ",
    "dashboard.unlockedBenefit": "उपलब्ध आर्थिक सहाय्य",
    "dashboard.satelliteCard": "उपग्रह जमीन माहिती",
    "dashboard.openGisMap": "सविस्तर GIS नकाशा उघडा →",
  },
  ta: {
    // Navigation
    "nav.home": "முகப்பு",
    "nav.signIn": "உள்நுழை",
    "nav.dashboard": "டாஷ்போர்டு",
    "nav.market": "சந்தை",
    "nav.mandi": "மண்டி",
    "nav.climate": "காலநிலை",
    "nav.yield": "விளைச்சல்",
    "nav.advisor": "ஆலோசகர்",
    "nav.subsidies": "மானியங்கள் & காப்பீடு",
    "nav.profile": "சுயவிவரம்",
    "nav.logOut": "வெளியேறு",
    "nav.signOut": "வெளியேறுதல்",
    "nav.signOutConfirm": "AgriSense இலிருந்து வெளியேற விரும்புகிறீர்களா?",
    "nav.cancel": "ரத்து",
    "nav.confirm": "உறுதி",
    "nav.language": "மொழி",

    // Common
    "common.refresh": "புதுப்பி",
    "common.save": "சேமி",
    "common.crop": "பயிர்",
    "common.state": "மாநிலம்",
    "common.season": "பருவம்",
    "common.acres": "ஏக்கர்",
    "common.low": "குறைந்த ஆபத்து",
    "common.moderate": "மிதமான ஆபத்து",
    "common.high": "அதிக ஆபத்து",
    "common.goodMorning": "காலை வணக்கம்",
    "common.yourFarm": "உங்கள் பண்ணை",
    "common.viewDetails": "விவரங்களை பார்க்க",
    "common.loading": "ஏற்றுகிறது...",
    "common.search": "தேடு",
    "common.all": "அனைத்தும்",

    // Crops
    "crop.Wheat": "கோதுமை",
    "crop.Rice": "அரிசி / நெல்",
    "crop.Maize": "மக்காச்சோளம்",
    "crop.Soybean": "சோயாபீன்",
    "crop.Cotton": "பருத்தி",
    "crop.Sugarcane": "கரும்பு",
    "crop.Tomato": "தக்காளி",
    "crop.Potato": "உருளைக்கிழங்கு",
    "crop.Mustard": "கடுகு",
    "crop.Chickpea": "சுண்டல் / கொண்டைக்கடலை",
    "crop.Onion": "வெங்காயம்",

    // Seasons
    "season.Rabi": "ரபி (குளிர்காலம்)",
    "season.Kharif": "காரீப் (மழைக்காலம்)",
    "season.Zaid": "ஜைத் (கோடைகாலம்)",

    // Days of week
    "day.Mon": "திங்கள்",
    "day.Tue": "செவ்வாய்",
    "day.Wed": "புதன்",
    "day.Thu": "வியாழன்",
    "day.Fri": "வெள்ளி",
    "day.Sat": "சனி",
    "day.Sun": "ஞாயிறு",

    // Landing Page
    "landing.heroTitle": "சிறந்த முடிவுகள் தான் புத்திசாலி வேளாண்மையின் தொடக்கம்",
    "landing.heroSubtitle": "AI மூலம் தேவை, விலை, மற்றும் காலநிலை ஆபத்துகளை கணிக்கவும். AgriSense நவீன விவசாயிக்காக உருவாக்கப்பட்ட நம்பகமான தளம்.",
    "landing.getStarted": "தொடங்குங்கள்",
    "landing.featureDemandTitle": "தேவை கணிப்பு",
    "landing.featureDemandDesc": "உங்கள் பயிர்களுக்கு சந்தை தேவை என்ன என்பதை துல்லியமாக கணித்து விற்பனை நேரத்தை திட்டமிடுங்கள்.",
    "landing.featurePriceTitle": "விலை கணிப்பு",
    "landing.featurePriceDesc": "சந்தை விலைகளை கண்காணித்து பெரிய ஏற்ற இறக்கங்களுக்கு முன் அறிவிப்புகளை பெறுங்கள்.",
    "landing.featureClimateTitle": "காலநிலை ஆபத்து எச்சரிக்கை",
    "landing.featureClimateDesc": "உள்ளூர் ஆபத்து குறிப்புகளுடன் வறட்சி, வெள்ளம், பனிப்பொழிவு போன்றவற்றை முன்கூட்டியே அறியுங்கள்.",
    "landing.howItWorks": "இது எப்படி செயல்படுகிறது",
    "landing.step1": "படி 1",
    "landing.step1Text": "பண்ணை தகவலை உள்ளிடுங்கள்",
    "landing.step2": "படி 2",
    "landing.step2Text": "AI போக்குகளை ஆய்வு செய்கிறது",
    "landing.step3": "படி 3",
    "landing.step3Text": "எளிய அறிவுரைகள் பெறுங்கள்",
    "landing.footer": "AgriSense மூலம் இயக்கப்படுகிறது",

    // Auth
    "signin.welcome": "மீண்டும் வரவேற்கிறோம்",
    "signin.subtitle": "உங்கள் பண்ணை நுண்ணறிவை அணுக உள்நுழையவும்.",
    "signin.email": "மின்னஞ்சல்",
    "signin.password": "கடவுச்சொல்",
    "signin.submit": "உள்நுழை",
    "signin.or": "அல்லது",
    "signin.google": "Google மூலம் தொடரவும்",
    "signin.tabSignIn": "உள்நுழை",
    "signin.tabSignUp": "கணக்கு தொடங்கு",
    "signin.demo": "டெமோ அணுகல்",
    "signin.noAccount": "AgriSense-க்கு புதியவரா? கணக்கை உருவாக்கவும்",
    "signin.haveAccount": "ஏற்கனவே கணக்கு உள்ளதா? உள்நுழையவும்",
    "signup.title": "விவசாயி கணக்கை உருவாக்கவும்",
    "signup.subtitle": "AI உதவியுடன் பயிர், சந்தை மற்றும் காலநிலை நுண்ணறிவை பெறுங்கள்.",
    "signup.name": "முழு பெயர்",
    "signup.location": "மாநிலம் / இருப்பிடம்",
    "signup.crop": "முதன்மையான பயிர்",
    "signup.acres": "பண்ணை அளவு (ஏக்கர்)",
    "signup.submit": "கணக்கை உருவாக்கி தொடங்கவும்",

    // Dashboard
    "dashboard.yourFarm": "உங்கள் பண்ணை",
    "dashboard.goodMorning": "காலை வணக்கம்",
    "dashboard.season": "பருவம்",
    "dashboard.refresh": "புதுப்பி",
    "dashboard.seasonProgress": "பருவ முன்னேற்றம் — 26 வாரங்களில் வாரம் 14",
    "dashboard.planting": "நடுதல்",
    "dashboard.growing": "வளர்ச்சி",
    "dashboard.harvest": "அறுவடை",
    "dashboard.pricePerQuintal": "விலை (குவிண்டாலுக்கு)",
    "dashboard.currentMarketData": "தற்போதைய சந்தை விவரம்",
    "dashboard.priceChange7d": "7 நாள் விலை மாற்றம்",
    "dashboard.comparedToLastWeek": "கடந்த வாரத்தை விட",
    "dashboard.marketVolatility": "சந்தை ஏற்ற இறக்கம்",
    "dashboard.basedOnRecentIndex": "சமீபத்திய குறியீட்டின் படி",
    "dashboard.climateRiskDetected": "காலநிலை ஆபத்து கண்டறியப்பட்டது",
    "dashboard.seeFullClimateReport": "முழு வானிலை அறிக்கை →",
    "dashboard.marketTellingYou": "சந்தை நுண்ணறிவு மற்றும் குறிப்புகள்",
    "dashboard.askAdvisorBtn": "AI ஆலோசகரிடம் கேட்க →",
    "dashboard.dataUpdated": "தரவு இப்போது புதுப்பிக்கப்பட்டது · AgriSense ML",

    // Market Page
    "market.title": "சந்தை நுண்ணறிவு மற்றும் பகுப்பாய்வு",
    "market.subtitle": "பயிர்களின் 30 நாள் விலை போக்கு மற்றும் 7 நாள் வேகத்தை கண்காணிக்கவும்.",
    "market.selectCrop": "பயிரை தேர்வு செய்க",
    "market.currentPrice": "தற்போதைய விலை",
    "market.change7d": "7 நாள் மாற்றம்",
    "market.rolling30d": "30 நாள் சராசரி",
    "market.volatility": "விலை ஏற்ற இறக்கம்",
    "market.trend30d": "30 நாள் விலை போக்கு",
    "market.perQtl": "/ குவிண்டால்",
    "market.velocity7d": "7 நாள் வேகம்",
    "market.volatilityScore": "ஏற்ற இறக்க மதிப்பெண்",
    "market.volatilityDesc": "விலை மாற்றங்கள் இந்த பருவத்திற்கான இயல்பான வரம்பிற்குள் உள்ளன.",

    // Mandi Page
    "mandi.tag": "மண்டி ஒப்பீடு",
    "mandi.title": "இன்று விற்க சிறந்த மண்டி",
    "mandi.subtitle": "நேரடி சந்தை விலைகள் · அதிக விலை தரும் சந்தையை தேர்ந்தெடுக்கவும்",
    "mandi.filterCommodity": "பயிர் வாரியாக வடிகட்டவும்",
    "mandi.all": "அனைத்து பயிர்கள்",
    "mandi.bestPriceToday": "இன்றைய சிறந்த விலை",
    "mandi.perQuintal": "குவிண்டாலுக்கு",
    "mandi.best": "சிறந்தது",
    "mandi.day7": "7-நாள்",
    "mandi.guideTitle": "அதிக லாபம் பெற மண்டி ஒப்பீட்டை எவ்வாறு பயன்படுத்துவது",
    "mandi.guide1": "சந்தை தேவை, வரத்து மற்றும் போக்குவரத்து செலவுகள் காரணமாக மண்டிகளிடையே விலைகள் வேறுபடுகின்றன. சரக்கை அனுப்புவதற்கு முன் விலையை ஒப்பிட்டு குவிண்டாலுக்கு ₹50–200 வரை கூடுதல் லாபம் பெறலாம்.",
    "mandi.guide2": "இன்று வெங்காயத்திற்கு நாசிக் மண்டி அதிக வேகத்தைக் காட்டுகிறது, தக்காளிக்கு டெல்லி மண்டி முன்னணியில் உள்ளது. போக்குவரத்து செலவை விட விலை வித்தியாசம் அதிகமாக இருந்தால் அங்கு விற்பது லாபகரமானது.",
    "mandi.guide3": "விலைகள் AGMARKNET பதிவுகளில் இருந்து தினமும் புதுப்பிக்கப்படுகின்றன. தக்காளி, வெங்காயம் போன்றவற்றுக்கு காலை கிளம்பும் முன் சரிபார்க்கவும்.",
    "mandi.footer": "தகவல் மூலம் mandi_prices.csv · தினமும் புதுப்பிக்கப்படுகிறது · AgriSense ML",

    // Climate Page
    "climate.tag": "வானிலை & காலநிலை ஆபத்து",
    "climate.title": "வானிலை முன்னறிவிப்பு & பண்ணை ஆபத்து",
    "climate.subtitle": "வரவிருக்கும் காலநிலை ஆபத்துகளை முன்கூட்டியே புரிந்து கொள்ளுங்கள்",
    "climate.forecast10d": "10 நாள் பண்ணை வானிலை முன்னறிவிப்பு",
    "climate.dry": "வறண்ட / வெயில்",
    "climate.lowRain": "குறைந்த மழை",
    "climate.modRain": "மிதமான மழை",
    "climate.heavyRain": "கனமழை",
    "climate.temp": "வெப்பநிலை",
    "climate.rainRisk": "மழை ஆபத்து",
    "climate.droughtRisk": "வறட்சி ஆபத்து",
    "climate.droughtText": "மண்ணின் ஈரப்பதம் வேகமாக குறைகிறது. பயிருக்கு நீர் பற்றாக்குறை ஏற்பட வாய்ப்புள்ளது.",
    "climate.floodRisk": "வெள்ள ஆபத்து",
    "climate.floodText": "கனமழைக்கு வாய்ப்பில்லை. வெள்ளம் அல்லது நீர் தேங்குதல் சாத்தியம் குறைவு.",
    "climate.frostRisk": "பனிப்பொழிவு ஆபத்து",
    "climate.frostText": "வெப்பநிலை 20°Cக்கு மேல் பாதுகாப்பான அளவில் இருக்கும்.",
    "climate.irrigationRec": "பாசன பரிந்துரை",
    "climate.irrigationText": "வறண்ட வானிலை காரணமாக, இந்த வாரம் செவ்வாய் மற்றும் வெள்ளிக்கிழமைகளில் பாசனம் செய்யவும். தேவையான நீர்: அமர்வுக்கு 18 மிமீ.",
    "climate.cropImpactTitle": "இந்த வானிலை உங்கள் பயிரை எவ்வாறு பாதிக்கிறது",
    "climate.cropImpactText1": "புதன் மற்றும் வியாழக்கிழமைகளில் எதிர்பார்க்கப்படும் வெப்பம் (34°C வரை) பயிரின் ஆரம்ப வளர்ச்சி நிலையை பாதிக்கலாம். மண்ணில் ஈரப்பதத்தை பராமரிப்பது முக்கியம்.",
    "climate.cropImpactText2": "வெள்ளிக்கிழமை மழை பெய்யக்கூடும் என்பதால், ஊட்டச்சத்துக்கள் அடித்துச் செல்லப்படாமல் இருக்க மழைக்கு முன் அதிக உரம் இடுவதைத் தவிர்க்கவும்.",
    "climate.historicalContext": "இந்த மாத மழைப்பொழிவு உங்கள் பகுதியின் 10 ஆண்டு சராசரியை விட 34% குறைவாக உள்ளது. முறையான பாசனத்தை உறுதி செய்யவும்.",

    // Yield Page
    "yield.title": "பயிர் விளைச்சல் மாதிரி கணிப்பான்",
    "yield.subtitle": "எதிர்பார்க்கப்படும் உற்பத்தியை கணிக்க தேவையான அளவுருக்களை சரிசெய்யவும்.",
    "yield.configureInputs": "அளவுருக்களை தேர்வு செய்க",
    "yield.crop": "பயிர்",
    "yield.season": "சாகுபடி பருவம்",
    "yield.rainfallVolume": "மழை அளவு",
    "yield.fertilizerFactor": "உர பயன்பாட்டு அளவு",
    "yield.fieldSize": "நில அளவு",
    "yield.liveEngine": "நேரடி கணிப்பு இயந்திரம்",
    "yield.totalExpectedAcross": "மொத்த எதிர்பார்க்கப்படும் விளைச்சல்",
    "yield.confidenceLevel": "நம்பகத்தன்மை அளவு",
    "yield.vsHistoricalAvg": "வரலாற்று சராசரியுடன் ஒப்பீடு",

    // Advisor Page
    "advisor.title": "AI வேளாண்மை ஆலோசகரிடம் கேளுங்கள்",
    "advisor.subtitle": "உங்கள் நிலம் மற்றும் நேரடி சந்தை தகவல்களின் அடிப்படையில் உடனடி நிபுணர் ஆலோசனை.",
    "advisor.placeholder": "சந்தை நேரம், வானிலை ஆபத்துகள் அல்லது விளைச்சல் பற்றி கேளுங்கள்...",
    "advisor.send": "அனுப்பு",
    "advisor.disclaimer": "AgriSense ML பதில்கள் வழிகாட்டுதல் நோக்கங்களுக்காக மட்டுமே",
    "advisor.prompt1": "இந்த வாரம் இருப்பு வைத்திருக்கும் கோதுமையை விற்கலாமா?",
    "advisor.prompt2": "பஞ்சாபில் ரபி பருவத்திற்கு எந்த பயிர் சிறந்தது?",
    "advisor.prompt3": "தற்போதைய வறண்ட வானிலை மண் ஈரப்பதத்தை எவ்வாறு பாதிக்கிறது?",
    "advisor.initialAssistant": "வணக்கம். நான் உங்கள் AgriSense AI வேளாண் ஆலோசகர். இன்று உங்கள் பண்ணை பணிகளில் நான் எவ்வாறு உதவ முடியும்?",
    "advisor.voiceInput": "பேசி கேட்கவும்",
    "advisor.listening": "கேட்கிறது...",
    "advisor.readOut": "கேளுங்கள்",
    "advisor.stopAudio": "ஆடியோவை நிறுத்துங்கள்",

    // Profile Page
    "profile.tag": "விவசாயி சுயவிவரம் & நில இருப்பிடம்",
    "profile.title": "உங்கள் பண்ணை சுயவிவரம்",
    "profile.subtitle": "துல்லியமான AI கணிப்புகளுக்கு பண்ணை தகவல், மண் மற்றும் நில இருப்பிடத்தை புதுப்பித்து வைக்கவும்.",
    "profile.verifiedLand": "சரிபார்க்கப்பட்ட நிலம்",
    "profile.farmer": "விவசாயி",
    "profile.formTitle": "பண்ணை மற்றும் மண் அளவுருக்கள்",
    "profile.syncedMap": "நில வரைபடத்துடன் தானாக இணைக்கப்பட்டது",
    "profile.fullName": "முழு பெயர்",
    "profile.state": "மாநிலம் / இருப்பிடம்",
    "profile.primaryCrop": "முதன்மையான பயிர்",
    "profile.totalArea": "மொத்த பண்ணை பரப்பு (ஏக்கர்)",
    "profile.currentSeason": "தற்போதைய பருவம்",
    "profile.soilClass": "மண் வகைப்பாடு (வரைபடத்திலிருந்து)",
    "profile.elevation": "நில உயரம்",
    "profile.metersAboveSea": "மீட்டர் கடல் மட்டத்திற்கு மேல்",
    "profile.summaryTitle": "செயலில் உள்ள நிலம் & பண்ணை சுருக்கம்",
    "profile.landArea": "நில பரப்பு",
    "profile.soil": "மண்",
    "profile.gpsPin": "GPS பின்",
    "profile.saveBtn": "சுயவிவரம் மற்றும் இருப்பிடத்தை சேமிக்கவும்",
    "profile.savedNotice": "சுயவிவரம் மற்றும் நில தகவல் வெற்றிகரமாக சேமிக்கப்பட்டது!",

    // Map Component
    "map.title": "பண்ணை நில இருப்பிடம்",
    "map.subtitle": "துல்லியமான உள்ளூர் வானிலை மற்றும் மண் பகுப்பாய்வுக்கு உங்கள் நிலத்தை வரைபடத்தில் குறிக்கவும்.",
    "map.gpsBtn": "எனது GPS இருப்பிடத்தைப் பயன்படுத்தவும்",
    "map.locating": "இருப்பிடம் கண்டறியப்படுகிறது...",
    "map.searchPlaceholder": "மாவட்டம், வட்டம் அல்லது ஊரை தேடவும் (எ.கா. லூதியானா, நாசிக், கர்னல்)...",
    "map.searchBtn": "தேடு",
    "map.searching": "தேடுகிறது...",
    "map.dragHint": "நில அமைப்பை மாற்ற வரைபடத்தில் கிளிக் செய்யவும் அல்லது குறியீட்டை நகர்த்தவும்",
    "map.cardElevation": "அச்சுரேகை & நில உயரம்",
    "map.altitude": "மீட்டர் உயரம்",
    "map.cardSoil": "மண் வகைப்பாடு",
    "map.cardClimate": "நேரடி பண்ணை வானிலை",
    "map.wind": "காற்று",
    "map.region": "பகுதி",
    "map.layerSatellite": "செயற்கைக்கோள் (Esri)",
    "map.layerTerrain": "நிலப்பரப்பு (OpenTopo)",
    "map.layerStreets": "நிலையான சாலை",
    "map.ndviVigor": "NDVI தாவர வீரியம்",
    "map.ndviHealthy": "ஆரோக்கியமான அடர்ந்த பயிர்",
    "map.ndviModerate": "மிதமான பயிர் அடர்த்தி",
    "map.soilHealth": "மண் ஈரம் மற்றும் நைட்ரஜன்",
    "map.elevationMeters": "மீட்டர் கடல் மட்டத்திற்கு மேல்",
    "map.switchLayer": "வரைபட அடுக்கு",

    // Command Center
    "dashboard.commandCenter": "பண்ணை கட்டுப்பாட்டு மையம்",
    "dashboard.estimatedRevenue": "மதிப்பிடப்பட்ட மொத்த அறுவடை வருவாய்",
    "dashboard.expectedOutput": "எதிர்பார்க்கப்படும் உற்பத்தி",
    "dashboard.livePrice": "நேரடி APMC மாதிரி விலை",
    "dashboard.arbitrageTitle": "மண்டி விலை இடைவெளி வாய்ப்பு",
    "dashboard.highestMarket": "அதிக விலை வழங்கும் APMC மண்டி",
    "dashboard.netSpread": "கூடுதல் லாபம்",
    "dashboard.perQtlMore": "ஒரு குவிண்டாலுக்கு அதிகம்",
    "dashboard.sprayWindow": "மருந்து தெளிப்பு சாதக நிலை",
    "dashboard.spraySafe": "தெளிப்பதற்கு உகந்த நேரம் (பாதுகாப்பானது)",
    "dashboard.sprayHazard": "வானிலை ஆபத்து (தெளிப்பை தவிர்க்கவும்)",
    "dashboard.cropDoctorCard": "ஸ்மார்ட் பயிர் மருத்துவர்",
    "dashboard.doctorQuickScan": "பயிர் நோய்களை கண்டறிந்து மருந்தளவை அறியவும்",
    "dashboard.subsidiesOverview": "அரசு மானியங்கள் & நிதி நன்மைகள்",
    "dashboard.unlockedBenefit": "கிடைக்கக்கூடிய நிதி உதவி",
    "dashboard.satelliteCard": "செயற்கைக்கோள் நில நுண்ணறிவு",
    "dashboard.openGisMap": "முழு GIS வரைபடத்தை திறக்க →",
  },
};

const languageOptions: { code: LanguageCode; label: string }[] = [
  { code: "en", label: "English" },
  { code: "hi", label: "Hindi (हिंदी)" },
  { code: "mr", label: "Marathi (मराठी)" },
  { code: "ta", label: "Tamil (தமிழ்)" },
];

export type LanguageContextType = {
  language: LanguageCode;
  setLanguage: (language: LanguageCode) => void;
  t: (key: string, fallback?: string) => string;
  options: { code: LanguageCode; label: string }[];
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<LanguageCode>("en");

  useEffect(() => {
    const storedLanguage = localStorage.getItem("agrisense_language") as LanguageCode | null;
    if (storedLanguage && translations[storedLanguage]) {
      setLanguage(storedLanguage);
    }
  }, []);

  const updateLanguage = (newLanguage: LanguageCode) => {
    setLanguage(newLanguage);
    localStorage.setItem("agrisense_language", newLanguage);
  };

  const t = useMemo(
    () => (key: string, fallback?: string) => {
      return translations[language]?.[key] || translations.en?.[key] || fallback || key;
    },
    [language]
  );

  const value: LanguageContextType = {
    language,
    setLanguage: updateLanguage,
    t,
    options: languageOptions,
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
